kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: raft-pvc
  namespace: raft
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: fabricfile
