

apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderer3
  labels:
    app: orderer3
  namespace: raft     
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderer3
  template:
    metadata:
      labels:
        app: orderer3
    spec:
      volumes:
        - name: fabricfile
          persistentVolumeClaim:
            claimName: raft-pvc        

      containers:
      - name: orderer
        image: hyperledger/fabric-orderer:latest
        imagePullPolicy: Always
        command: ["sh", "-c", "orderer"]
        env:
            - name: ORDERER_CFG_PATH
              value: /fabric/
            - name: CONFIGTX_ORDERER_ADDRESSES
              value: "orderer3.example.com:7050"
            - name: ORDERER_GENERAL_LEDGERTYPE
              value: file
            - name: ORDERER_FILELEDGER_LOCATION
              value: /fabric/ledger/orderer3
            - name: ORDERER_GENERAL_BATCHTIMEOUT
              value: 1s
            - name: ORDERER_GENERAL_BATCHSIZE_MAXMESSAGECOUNT
              value: "10"
            - name: ORDERER_GENERAL_MAXWINDOWSIZE
              value: "1000"
            - name: ORDERER_GENERAL_ORDERERTYPE
              value: etcdraft
            - name: ORDERER_GENERAL_LISTENADDRESS
              value: 0.0.0.0
            - name: ORDERER_GENERAL_LISTENPORT
              value: "7050"
            - name: ORDERER_GENERAL_LOGLEVEL
              value: debug
            - name: ORDERER_GENERAL_LOCALMSPDIR
              value: /fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/msp
            - name: ORDERER_GENERAL_LOCALMSPID
              value: OrdererMSP
            - name: ORDERER_GENERAL_GENESISMETHOD
              value: file
            - name: ORDERER_GENERAL_GENESISFILE
              value: /fabric/genesis.block
            - name: ORDERER_GENERAL_GENESISPROFILE
              value: initial
            - name: ORDERER_GENERAL_TLS_ENABLED
              value: "true"
            - name: GODEBUG
              value: "netdns=go"
            - name: ORDERER_GENERAL_TLS_CERTIFICATE
              value: "/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/tls/server.crt"
            - name: ORDERER_GENERAL_TLS_PRIVATEKEY
              value: "/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/tls/server.key"

            - name: ORDERER_GENERAL_TLS_ROOTCAS
              value: "/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/tls/ca.crt"
            - name: ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
              value: "/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/tls/server.crt"
            - name: ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
              value: "/fabric/crypto-config/ordererOrganizations/example.com/orderers/orderer3.example.com/tls/server.key"

        volumeMounts:
            - mountPath: /fabric
              name: fabricfile      
